services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      - app_network
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .d
      dockerfile: frontend/books-web/Dockerfile
    networks:
      - app_network
    ports:
      - "8080:80"

    depends_on:
      - backend

networks:
  app_network:
    driver: bridge
