# build react
FROM node:22 AS build

WORKDIR /app

COPY frontend/books-web/package*.json ./
RUN npm install

COPY frontend/books-web .
RUN npm run build

# nginx serve
FROM nginx:latest

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]